<a href="https://colab.research.google.com/github/sayarghoshroy/Analysis/blob/main/discriminant_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# $Problem\ 4$

In [2]:
data_males = [[15, 17, 24, 14],
              [17, 15, 32, 26],
              [15, 14, 29, 23],
              [13, 12, 10, 16],
              [20, 17, 26, 28],
              [15, 21, 26, 21],
              [15, 13, 26, 22],
              [13, 5, 22, 22],
              [14, 7, 30, 17],
              [17, 15, 30, 27],
              [17, 17, 26, 20],
              [17, 20, 28, 24],
              [15, 15, 29, 24],
              [18, 19, 32, 28],
              [18, 18, 31, 27],
              [15, 14, 26, 21],
              [18, 17, 33, 26],
              [10, 14, 19, 17],
              [18, 21, 30, 29],
              [18, 21, 34, 26],
              [13, 17, 30, 24],
              [16, 16, 16, 16],
              [11, 15, 25, 23],
              [16, 13, 26, 16],
              [16, 13, 23, 21],
              [18, 18, 34, 24],
              [16, 15, 28, 27],
              [15, 16, 29, 24],
              [18, 19, 32, 23],
              [18, 16, 33, 23],
              [17, 20, 21, 21],
              [19, 19, 30, 28]]

data_females = [[13, 14, 12, 21],
                [14, 12, 14, 26],
                [12, 19, 21, 21],
                [12, 13, 10, 16],
                [11, 20, 16, 16],
                [12, 9, 14, 18],
                [10, 13, 18, 24],
                [10, 8, 13, 23],
                [12, 20, 19, 23],
                [11, 10, 11, 27],
                [12, 18, 25, 25],
                [14, 18, 13, 26],
                [14, 10, 25, 28],
                [13, 16, 23, 28],
                [16, 21, 26, 26],
                [14, 17, 14, 14],
                [16, 16, 15, 23],
                [13, 16, 23, 24],
                [2, 6, 16, 21],
                [14, 16, 22, 26],
                [14, 17, 22, 28],
                [16, 13, 16, 14],
                [15, 14, 20, 26],
                [12, 10, 12, 9],
                [14, 17, 24, 23],
                [13, 15, 18, 20],
                [11, 16, 18, 28],
                [7, 7, 19, 18],
                [12, 15, 7, 28],
                [6, 5, 6, 13]]

data_females = np.asarray(data_females)
data_males = np.asarray(data_males)

count_females = np.shape(data_females)[0]
count_males = np.shape(data_females)[0]
total_count = count_females + count_males

mean_females = np.mean(data_females, axis = 0)
mean_males = np.mean(data_males, axis = 0)

covariance_females = np.cov(data_females.T)
covariance_males = np.cov(data_males.T)

pooled_covariance = ((count_females - 1) * covariance_females +
                     (count_males - 1) * covariance_males) / (total_count - 2)

disc_coeff_vector = np.matmul(np.linalg.inv(pooled_covariance), (mean_males - mean_females))

print('Required Discriminant Function Coefficient Vector:')
print(np.round(disc_coeff_vector, 4))

Required Discriminant Function Coefficient Vector:
[ 0.5621 -0.2294  0.4412 -0.2863]


# $Problem\ 5$

In [3]:
method_1 = [[5.4, 6.0, 6.3, 6.7],
            [5.2, 6.2, 6.0, 5.8],
            [6.1, 5.9, 6.0, 7.0],
            [4.8, 5.0, 4.9, 5.0],
            [5.0, 5.7, 5.0, 6.5],
            [5.7, 6.1, 6.0, 6.6],
            [6.0, 6.0, 5.8, 6.0],
            [4.0, 5.0, 4.0, 5.0],
            [5.7, 5.4, 4.9, 5.0],
            [5.6, 5.2, 5.4, 5.8],
            [5.8, 6.1, 5.2, 6.4],
            [5.3, 5.9, 5.8, 6.0]]

method_2 = [[5.0, 5.3, 5.3, 6.5],
            [4.8, 4.9, 4.2, 5.6],
            [3.9, 4.0, 4.4, 5.0],
            [4.0, 5.1, 4.8, 5.8],
            [5.6, 5.4, 5.1, 6.2],
            [6.0, 5.5, 5.7, 6.0],
            [5.2, 4.8, 5.4, 6.0],
            [5.3, 5.1, 5.8, 6.4],
            [5.9, 6.1, 5.7, 6.0],
            [6.1, 6.0, 6.1, 6.2],
            [6.2, 5.7, 5.9, 6.0],
            [5.1, 4.9, 5.3, 4.8]]

method_3 = [[4.8, 5.0, 6.5, 7.0],
            [5.4, 5.0, 6.0, 6.4],
            [4.9, 5.1, 5.9, 6.5],
            [5.7, 5.2, 6.4, 6.4],
            [4.2, 4.6, 5.3, 6.3],
            [6.0, 5.3, 5.8, 5.4],
            [5.1, 5.2, 6.2, 6.5],
            [4.8, 4.6, 5.7, 5.7],
            [5.3, 5.4, 6.8, 6.6],
            [4.6, 4.4, 5.7, 5.6],
            [4.5, 4.0, 5.0, 5.9],
            [4.4, 4.2, 5.6, 5.5]]

method_1 = np.asarray(method_1)
method_2 = np.asarray(method_2)
method_3 = np.asarray(method_3)
methods = [method_1, method_2, method_3]

all_data = np.vstack(methods)

# As there are three methods
k = 3
n = methods[0].shape[0]
p = methods[0].shape[1]

total_mean = np.mean(all_data, 0)
means = []

for method in methods:
  means.append(np.mean(method, 0))

In [4]:
# Computing between Sum of Squares
H = np.zeros((p, p))
for mean in means:
  unit = np.asmatrix(mean - total_mean)
  print(unit)
  H += np.matmul(unit.T, unit)

H = n * H

[[ 0.17777778  0.45       -0.11111111 -0.01944444]]
[[ 0.05277778 -0.025      -0.24444444 -0.12777778]]
[[-0.23055556 -0.425       0.35555556  0.14722222]]


In [5]:
# Computing within Sum of Squares
E = np.zeros((p, p))

for i in range(k):
  for j in range(n):
    unit = np.asmatrix(methods[i][j] - means[i])
    E += np.matmul(unit.T, unit)

consider = np.matmul(np.linalg.inv(E), H)

In [6]:
# Computing eigenvectors of inverse(E).H

eigen_values, eigen_vectors = np.linalg.eig(consider)
positions = np.argsort(-1 * eigen_values)

for vector_index, index in enumerate(positions):
  print('Eigen Vector ' + str(vector_index + 1) + ' = ')
  print(np.round(eigen_vectors[:, index], 4))
  print()

Eigen Vector 1 = 
[-0.013   0.8274 -0.5496 -0.1149]

Eigen Vector 2 = 
[ 0.6057 -0.5857 -0.5088  0.1767]

Eigen Vector 3 = 
[-0.2557  0.0156 -0.4918  0.8322]

Eigen Vector 4 = 
[ 0.8065 -0.3107 -0.0554  0.4999]



In [7]:
# ^_^ Thank You